import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        primary: "#46f1c5",
        "primary-container": "#00d4aa",
        "on-primary": "#00382b",
        "on-primary-fixed": "#002118",
        "on-primary-fixed-variant": "#00513f",
        "primary-fixed": "#55fcd0",
        "primary-fixed-dim": "#28dfb5",
        secondary: "#c7bfff",
        "secondary-container": "#4327c4",
        "on-secondary": "#2a009f",
        "secondary-fixed": "#e4dfff",
        "secondary-fixed-dim": "#c7bfff",
        "on-secondary-container": "#b8afff",
        "on-secondary-fixed": "#170065",
        "on-secondary-fixed-variant": "#4024c2",
        tertiary: "#ffcea6",
        "tertiary-container": "#ffa858",
        "on-tertiary": "#4c2700",
        "tertiary-fixed": "#ffdcc1",
        "tertiary-fixed-dim": "#ffb77a",
        "on-tertiary-fixed": "#2e1500",
        "on-tertiary-fixed-variant": "#6c3a00",
        "on-tertiary-container": "#733e00",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        surface: "#10131c",
        "surface-dim": "#10131c",
        "surface-bright": "#353943",
        "surface-container-lowest": "#0a0e16",
        "surface-container-low": "#181c24",
        "surface-container": "#1c2028",
        "surface-container-high": "#262a33",
        "surface-container-highest": "#31353e",
        "surface-variant": "#31353e",
        "surface-tint": "#28dfb5",
        "on-surface": "#e0e2ee",
        "on-surface-variant": "#bacac2",
        "on-background": "#e0e2ee",
        background: "#10131c",
        outline: "#85948d",
        "outline-variant": "#3b4a44",
        "inverse-surface": "#e0e2ee",
        "inverse-on-surface": "#2d303a",
        "inverse-primary": "#006b55",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
        sans: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
